New readme section on how to use permissions for CRUD controllers
Laravel-Backpack/PermissionManager pull request #268
Opened 2021-02-16 16:24 UTC by Polfo

I spent some time finding out how to integrate Permissions with CRUD controllers. It is now documented and could be useful for other users.
Here are some related questions without answer:
https://stackoverflow.com/questions/65469302/laravel-backpack-rolewise-permission-give-to-module
https://stackoverflow.com/questions/57982478/laravel-backpackcrud-set-permission-role-to-a-category
https://stackoverflow.com/questions/55489878/cannot-restrict-access-to-permission-manager-routes-using-role-based-middleware
Did someone publish an alternative elsewhere? 
Can you accept this proposal? There are many ways to do it, but this may help getting started. It is the kind of documentation I missed.

2021-02-16 16:26 UTC, Polfo commented on README.md
> +Admin interface for [spatie/laravel-permission](https://github.com/spatie/laravel-permission). It allows admins to easily add/edit/remove users, roles and permissions, using [Laravel Backpack](https:
My editor always removes trailing spaces on save.

2023-10-11 12:11 UTC, tabacitu requested changes

2023-10-11 12:11 UTC, tabacitu commented on README.md
> +CRUD controllers have methods to [dynamically allow or deny access](https://backpackforlaravel.com/docs/4.1/crud-api#access) to operations. The ```$this->crud->allowAccess()``` and ```$this->crud->de
```suggestion
CRUD controllers have methods to [dynamically allow or deny access](https://backpackforlaravel.com/docs/6.x/crud-api#access) to operations. The ```$this->crud->allowAccess()``` and ```$this->crud->denyAccess()``` methods control both:
```

2023-10-11 12:11 UTC, tabacitu commented on README.md
> +Reminder: permissions can be assigned to a user either directly or through a role.
```suggestion
In most cases, you should use `access` and `permission` separately. But if you want to link them together, so a "permission" gives "access", here is how you can do that too. Reminder: permissions can be assigned to a user either directly or through a role.
```

2023-10-11 12:13 UTC, tabacitu commented
Wow, this is VERY GOOD. Thanks a lot @Polfo , I've just given this a read and merged it, super-useful. Thanks again @Polfo and sorry for taking so long to merge, must have slipped through the cracks.

Cheers!

2023-10-11 12:13 UTC, merged